# Generated by Django 5.0 on 2026-09-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='has_completed_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
