# Generated by Django 5.0 on 2026-09-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending_confirmation', 'Pending confirmation'), ('awaiting_payment', 'Awaiting payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('ready_for_delivery', 'Ready for delivery'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
