# Generated by Django 5.0 on 2026-09-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_membership_membership_unique_business_membership'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['business', 'created_at'], name='crm_custome_busines_946a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['business', 'phone_number'], name='crm_custome_busines_c68618_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('business', 'phone_number'), name='unique_customer_phone_per_business'),
        ),
    ]
