# Generated by Django 5.0 on 2026-09-10 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('whatsapp', '0002_conversation_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='crm.customer'),
        ),
    ]
