# Generated by Django 5.0 on 2026-09-16 14:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_membership_membership_unique_business_membership'),
        ('whatsapp', '0003_alter_conversation_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='whatsapp', max_length=50)),
                ('external_event_id', models.CharField(max_length=255, unique=True)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='whatsappmessage',
            options={'ordering': ['timestamp', 'id']},
        ),
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number_id', models.CharField(max_length=100, unique=True)),
                ('business_account_id', models.CharField(blank=True, max_length=100)),
                ('display_phone_number', models.CharField(blank=True, max_length=30)),
                ('access_token', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_accounts', to='accounts.business')),
            ],
        ),
    ]
