# Generated by Django 5.0 on 2026-09-16 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_membership_membership_unique_business_membership'),
        ('crm', '0002_alter_customer_options_alter_customer_phone_number_and_more'),
        ('whatsapp', '0004_webhookevent_alter_whatsappmessage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='unread_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=20),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['business', 'status', 'last_message_at'], name='whatsapp_co_busines_91d573_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['business', 'assigned_to'], name='whatsapp_co_busines_9b46ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('business', 'customer'), name='unique_conversation_per_customer'),
        ),
    ]
