# Generated by Django 5.0 on 2026-09-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_membership_membership_unique_business_membership'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'name'], name='inventory_p_busines_c181c4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'category'], name='inventory_p_busines_c24ca0_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('sku__isnull', False), models.Q(('sku', ''), _negated=True)), fields=('business', 'sku'), name='unique_product_sku_per_business'),
        ),
    ]
