# Generated by Django 5.0 on 2026-09-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_business_and_mpesa_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_busines_0cb2e2_idx',
            old_name='payments_pa_busines_4f4b5e_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_busines_92f879_idx',
            old_name='payments_pa_busines_8f4fb1_idx',
        ),
    ]
